%PDF-1.3
%“Œ‹ž ReportLab Generated PDF document http://www.reportlab.com
1 0 obj
<<
/F1 2 0 R /F2 3 0 R /F3 4 0 R
>>
endobj
2 0 obj
<<
/BaseFont /Helvetica /Encoding /WinAnsiEncoding /Name /F1 /Subtype /Type1 /Type /Font
>>
endobj
3 0 obj
<<
/BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding /Name /F2 /Subtype /Type1 /Type /Font
>>
endobj
4 0 obj
<<
/BaseFont /Courier /Encoding /WinAnsiEncoding /Name /F3 /Subtype /Type1 /Type /Font
>>
endobj
5 0 obj
<<
/Contents 11 0 R /MediaBox [ 0 0 595.2756 841.8898 ] /Parent 10 0 R /Resources <<
/Font 1 0 R /ProcSet [ /PDF /Text /ImageB /ImageC /ImageI ]
>> /Rotate 0 /Trans <<

>> 
  /Type /Page
>>
endobj
6 0 obj
<<
/Contents 12 0 R /MediaBox [ 0 0 595.2756 841.8898 ] /Parent 10 0 R /Resources <<
/Font 1 0 R /ProcSet [ /PDF /Text /ImageB /ImageC /ImageI ]
>> /Rotate 0 /Trans <<

>> 
  /Type /Page
>>
endobj
7 0 obj
<<
/Contents 13 0 R /MediaBox [ 0 0 595.2756 841.8898 ] /Parent 10 0 R /Resources <<
/Font 1 0 R /ProcSet [ /PDF /Text /ImageB /ImageC /ImageI ]
>> /Rotate 0 /Trans <<

>> 
  /Type /Page
>>
endobj
8 0 obj
<<
/PageMode /UseNone /Pages 10 0 R /Type /Catalog
>>
endobj
9 0 obj
<<
/Author (anonymous) /CreationDate (D:20250929005157+00'00') /Creator (ReportLab PDF Library - www.reportlab.com) /Keywords () /ModDate (D:20250929005157+00'00') /Producer (ReportLab PDF Library - www.reportlab.com) 
  /Subject (unspecified) /Title (untitled) /Trapped /False
>>
endobj
10 0 obj
<<
/Count 3 /Kids [ 5 0 R 6 0 R 7 0 R ] /Type /Pages
>>
endobj
11 0 obj
<<
/Filter [ /ASCII85Decode /FlateDecode ] /Length 965
>>
stream
Gatm:@;hVh&H1HmEU&=YSQ^Vr!3&q3l^CRK];/'Pek),R#Fr^?fZ9GWq=cZV,n<MY6*!OE1?REKHbOhr@&b:uT4%e?&O>Ld!O<i8!-/JQJm7FD#N`N#a=l*rA@S+O["@M1i:W2jq`V>9JYQur$BbrIE=A0rS.dWN0nCI6>YlC^6gt>4O)+7`6$7-J!tT!#K8>;.&HF5CJk()W1-O'U//MPZ).\o+0OC(F-a97a"sR[gO4>TJN0?(FRB`<D*nSg!p2N'mn8P1b)-NorR1sop.;'MLAlWB);Dn\=,7nn7!+eR6,\Q3k*#nS1'sgY<]PI<>Mapq`pF?.[>`FKqhue?EhYl0G,q@ki_qKfc9lP6K8t^u6<0CCPnec!BBS*/#.,e/8.95gD<n1.<"I;.dO=_1\8\mUJ/p4'U)gZ'Zk.^CKQ&k+ZnmPJ>T$MAWGU30_.6_gDc"CUb#'BE0FKuc"Uf1`EAhr%"D#`SN[B2LI\">>M\':=1)Gg`;SXb@(*+=\4`Ec%o4<>)EC7IP`BWS-pJM\/lccG-d@og3)Y77O<^KXKZPL'&uP5`q1CQ+?&LG.\4Frb3qbP>R3<$N,0;YB@e='n8Bg](QemTR<8ej"qbS'1+pA$rqG#.4M`N6&$&</'q<k(j?WW[YG/Ad==:)k4n43Gi;MHtt[ms'Sf]nB;nIRa3n4p?VYN#<s,JmiW'/!N\d0@8BjA<]\25<o,Vb`n:/bDq]',\+T:GNdBIGD-&goH9HNJI5`,LkJ$c_B<Lt=MV30^Y1Vt8TWqradU3c>11LsZ;Mg$k-:rel"B`N#Vf;j&-Cag5GV5"daS8.U'Or_LUMZH:UpGIKXjU@`fbJ)YFC(=9S=VKb)QLWPNasbK!SCn/bsf!_/[#+m2n\T<f$Vo/Y/4;uc)SmPEZo5-T`nHm`DkY9(i\&.51Im4OR?uQj?pM\m:Te`XkVEaS#u[CK>4h3q;M~>endstream
endobj
12 0 obj
<<
/Filter [ /ASCII85Decode /FlateDecode ] /Length 970
>>
stream
Gatn%lV?2"&;C/U'N;'49%>oXopl.^!(0V)6&@seTW/cSSS[C\j9m8PhmGfba2ELl.ZtO+GE-=Vh]<:0M>pClFTR(,)qsH\&-gkkUkfB1?*N\/,*$rELhi`iMPDO*<<CuEU1'GeAcNoC.@hK0e[L;m=+e]1%3ON8GIA%UDm2GX2>ORTTdbop\YdA(oo`oYc(uHhB`dO`69nWY:)!gVFN+/,0T2\2k478S)9Mdj83Fuq)Q!g/nT&?O(`CPl(2;7sFC'm*X_Kj<%XJ[]=SR,+r#)\L?*0Wo.''`DKAj;Gb9=7!,]4u.'%;"Id[m=e?S<S_Q,MqFl39WflW7Sqe?^5uK96=l<52Zn2R`B]-n5loK@$%m5ATjJZdb;RqmV/MBFok/H/=m&iYsl*1o8>lDqq`R>9gb$@5UMF/,-g!Bje%g,ngX[)=uYeI%%o7armB6&sMr:%\+)dZS5qk"W$V#$$[F2l?UT^1j%l>q9cELiFbFdF@M1$d^[$5871Hga*jW+1]lWTMN5GLhiGR2UB!ouH["-)pB3I12@Ege.)#tS-E0Z6N=/]ahM-I/5eF>*C1`1u<\*(od8S62ql:cq2o)<5H53mS6$M+"cC%jb710Rm5E=(aR/hd\i\82"@f2[I1o#'-P*DG6mR]i/>]<8,)KV`IGaioPR*r/+7a[2"^8,FG'44X:j]OfdKoH8Mi(f/]GB,W2QN")"aeho=Xu!_(9Uf:)4Vq4L&W:/H.W"F%`/NLK4F$VJAY)EPS@69`XT%nKIUgf:D(?Ea<O?(J;<+j8qufFHOaohkW)&^PkJ,b3Z+BEXnbnnO]`Qc/"^OT4"41UNIMMK6OFm.<o@/"q%3)'obO*Uj+IQ)^H&RCGB?H_nA-r!-rio\O;be%(I&,aF5"@Uiamhs$PJo)DDZL<5[i1_ihK`qSW6*\F-#*;k93er>9^<+=H2b!*'cBK;_lkBMY?2t7r<3ZqlNd~>endstream
endobj
13 0 obj
<<
/Filter [ /ASCII85Decode /FlateDecode ] /Length 434
>>
stream
Garo<95DC0'SZ;\MF1E]Bc`ION#!537MHpV*G@mQ(uiK0j<;WI>km>@%Aeo`@:8#bHgc/j%Y5c6.;qEO?7>G#!AQkBOLE^ES\q;+;E(FMlF,hS3r)'`%!6haF.Ah<-Fhe9IdCS(50rJ(3,s_[HdE;MLL6RY+XPF^bl9Y,ijq!P%>6kTU6HI%n?XBKkoM%$i.[88.[]Sa#W[f3W;ST]cmq8=>@6Sdc]2:VNn<+hkoi[FI23nNp6o#hCU^@P=)U5@:"R`f7BRFMbILqGoM?fQ1Vtmt`6__*Tg<Ic2N;J*I9Ut9(QQm*DE,,#<7NB34TAs^^bQ7"MC@H:8IV[%_o2o\.?C/,#_b83FZn#t(5H$9FBgHVk=C+[RbGGYQL9p=[juC.Ut@,-*6KK?oq8rVmlRpR^E9d\p5CA%MC]%)XqoF]!hZp+&c~>endstream
endobj
xref
0 14
0000000000 65535 f 
0000000073 00000 n 
0000000124 00000 n 
0000000231 00000 n 
0000000343 00000 n 
0000000448 00000 n 
0000000653 00000 n 
0000000858 00000 n 
0000001063 00000 n 
0000001132 00000 n 
0000001428 00000 n 
0000001500 00000 n 
0000002556 00000 n 
0000003617 00000 n 
trailer
<<
/ID 
[<c9efcbc3dc3038b1be7c49af24b8fbf3><c9efcbc3dc3038b1be7c49af24b8fbf3>]
% ReportLab generated PDF document -- digest (http://www.reportlab.com)

/Info 9 0 R
/Root 8 0 R
/Size 14
>>
startxref
4142
%%EOF
